import { useEffect, useState, useMemo } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ContactForm } from "@/components/ContactForm";
import { ENTERPRISE_CATEGORIES } from "@/components/home/EnterpriseDataStrip";
import { ArrowLeft, CheckCircle2, Sparkles, TrendingUp } from "lucide-react";
import flowpulseLogo from "@/assets/flowpulse-logo.png";
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from "recharts";

interface Explainer {
  headline: string;
  intro: string;
  sections: { title: string; body: string }[];
  capabilities: string[];
  dataPoints: { label: string; value: string }[];
  useCases: { title: string; description: string }[];
}

// Per-category visual presets — generic but topical so it loads instantly
const VISUAL_PRESETS: Record<
  string,
  {
    primary: string;
    accent: string;
    chart: "area" | "bar" | "line" | "radar" | "pie" | "stacked";
    chartTitle: string;
    chartData: any[];
    fallbackHeadline: string;
    fallbackIntro: string;
    fallbackPoints: { label: string; value: string }[];
  }
> = {
  "market-commentary": {
    primary: "hsl(217 91% 60%)",
    accent: "hsl(199 89% 60%)",
    chart: "area",
    chartTitle: "Daily commentary publishing volume",
    chartData: Array.from({ length: 12 }, (_, i) => ({
      name: `M${i + 1}`,
      value: 40 + Math.round(Math.sin(i / 1.5) * 15) + i * 3,
    })),
    fallbackHeadline: "Institutional-grade market intelligence, on demand",
    fallbackIntro:
      "FlowPulse delivers continuous market commentary across asset classes, generated by our AI analyst desk and curated by sector specialists.",
    fallbackPoints: [
      { label: "Asset classes", value: "12+" },
      { label: "Daily updates", value: "100+" },
      { label: "Languages", value: "8" },
      { label: "Latency", value: "<5min" },
    ],
  },
  benchmarking: {
    primary: "hsl(142 71% 45%)",
    accent: "hsl(200 89% 60%)",
    chart: "bar",
    chartTitle: "Portfolio vs benchmark — trailing 12m",
    chartData: [
      { name: "Q1", portfolio: 6.2, benchmark: 4.8 },
      { name: "Q2", portfolio: 8.1, benchmark: 6.4 },
      { name: "Q3", portfolio: 5.5, benchmark: 5.9 },
      { name: "Q4", portfolio: 9.7, benchmark: 7.1 },
    ],
    fallbackHeadline: "Quantify performance against the universe that matters",
    fallbackIntro:
      "Benchmark portfolios, funds and strategies against custom peer groups, indices and risk-adjusted reference sets in seconds.",
    fallbackPoints: [
      { label: "Indices", value: "5,000+" },
      { label: "Peer groups", value: "Custom" },
      { label: "Metrics", value: "40+" },
      { label: "Refresh", value: "Daily" },
    ],
  },
  "model-portfolios": {
    primary: "hsl(262 83% 58%)",
    accent: "hsl(199 89% 60%)",
    chart: "pie",
    chartTitle: "Sample model — asset allocation",
    chartData: [
      { name: "Equities", value: 55 },
      { name: "Fixed Income", value: 25 },
      { name: "Alternatives", value: 12 },
      { name: "Cash", value: 8 },
    ],
    fallbackHeadline: "Model portfolios, governed and ready to deploy",
    fallbackIntro:
      "Curated model portfolios across risk profiles, with full transparency on holdings, factor exposure and rebalance history.",
    fallbackPoints: [
      { label: "Models", value: "60+" },
      { label: "Risk bands", value: "1-7" },
      { label: "Rebalances", value: "Quarterly" },
      { label: "Coverage", value: "Global" },
    ],
  },
  watchlists: {
    primary: "hsl(38 92% 50%)",
    accent: "hsl(217 91% 60%)",
    chart: "line",
    chartTitle: "Watchlist signals fired (last 30 days)",
    chartData: Array.from({ length: 14 }, (_, i) => ({
      name: `D${i + 1}`,
      value: 8 + Math.round(Math.cos(i / 2) * 5) + Math.round(Math.random() * 4),
    })),
    fallbackHeadline: "Track the universe that matters to your book",
    fallbackIntro:
      "Build, share and monitor watchlists across equities, ETFs, funds and private deals — with real-time alerts on the moves you care about.",
    fallbackPoints: [
      { label: "Symbols", value: "Unlimited" },
      { label: "Alert types", value: "20+" },
      { label: "Channels", value: "Email/SMS/Push" },
      { label: "Latency", value: "Real-time" },
    ],
  },
  "screeners-discovery": {
    primary: "hsl(199 89% 48%)",
    accent: "hsl(262 83% 58%)",
    chart: "stacked",
    chartTitle: "Universe coverage by asset class",
    chartData: [
      { name: "Equities", listed: 45000, private: 12000 },
      { name: "Funds", listed: 32000, private: 4000 },
      { name: "ETFs", listed: 11000, private: 0 },
      { name: "Bonds", listed: 28000, private: 8000 },
      { name: "Alts", listed: 6000, private: 15000 },
    ],
    fallbackHeadline: "Discover, filter and shortlist with surgical precision",
    fallbackIntro:
      "Multi-factor screeners across listed and private universes, powered by 200+ filters and AI-assisted natural-language search.",
    fallbackPoints: [
      { label: "Filters", value: "200+" },
      { label: "Securities", value: "150K+" },
      { label: "Saved screens", value: "Unlimited" },
      { label: "AI search", value: "Built-in" },
    ],
  },
  "opportunity-intelligence": {
    primary: "hsl(346 87% 50%)",
    accent: "hsl(38 92% 50%)",
    chart: "area",
    chartTitle: "Live opportunities surfaced (12 weeks)",
    chartData: Array.from({ length: 12 }, (_, i) => ({
      name: `W${i + 1}`,
      value: 25 + i * 4 + Math.round(Math.sin(i) * 6),
    })),
    fallbackHeadline: "Proprietary deal flow, surfaced in real time",
    fallbackIntro:
      "Continuous AI-driven scanning of public, private and alternative markets to surface investable opportunities the moment they appear.",
    fallbackPoints: [
      { label: "Sources", value: "10K+" },
      { label: "New / week", value: "200+" },
      { label: "Sectors", value: "All" },
      { label: "Validation", value: "Human + AI" },
    ],
  },
  "signals-alerts": {
    primary: "hsl(0 84% 60%)",
    accent: "hsl(38 92% 50%)",
    chart: "bar",
    chartTitle: "Signal categories triggered (last quarter)",
    chartData: [
      { name: "Price", value: 1240 },
      { name: "News", value: 890 },
      { name: "Filings", value: 410 },
      { name: "Sector", value: 720 },
      { name: "Macro", value: 320 },
    ],
    fallbackHeadline: "Never miss a market-moving event",
    fallbackIntro:
      "Multi-channel alerting on price, fundamentals, filings, news and macro signals — routed to email, SMS, push and webhooks.",
    fallbackPoints: [
      { label: "Signal types", value: "30+" },
      { label: "Channels", value: "5" },
      { label: "Latency", value: "<2s" },
      { label: "Custom rules", value: "Unlimited" },
    ],
  },
  "fund-etf-database": {
    primary: "hsl(173 80% 40%)",
    accent: "hsl(199 89% 60%)",
    chart: "radar",
    chartTitle: "Fund profile — risk vs return factors",
    chartData: [
      { factor: "Return", A: 82 },
      { factor: "Sharpe", A: 74 },
      { factor: "Cost", A: 88 },
      { factor: "Liquidity", A: 91 },
      { factor: "ESG", A: 68 },
      { factor: "Drawdown", A: 79 },
    ],
    fallbackHeadline: "Verified fund and ETF intelligence — globally",
    fallbackIntro:
      "A curated database of institutional-grade funds and ETFs with deep factor analytics, holdings transparency and cost benchmarks.",
    fallbackPoints: [
      { label: "Funds", value: "30K+" },
      { label: "ETFs", value: "11K+" },
      { label: "Factors", value: "60+" },
      { label: "Update", value: "Daily" },
    ],
  },
  "learning-hub": {
    primary: "hsl(280 75% 55%)",
    accent: "hsl(217 91% 60%)",
    chart: "line",
    chartTitle: "Learner engagement (rolling 90 days)",
    chartData: Array.from({ length: 12 }, (_, i) => ({
      name: `W${i + 1}`,
      value: 60 + i * 5 + Math.round(Math.sin(i / 2) * 8),
    })),
    fallbackHeadline: "Continuous education for the modern investment desk",
    fallbackIntro:
      "Structured learning paths, expert-led courses and CPD-accredited content — built for advisors, analysts and institutional teams.",
    fallbackPoints: [
      { label: "Courses", value: "120+" },
      { label: "CPD hours", value: "300+" },
      { label: "Experts", value: "40+" },
      { label: "Languages", value: "6" },
    ],
  },
};

function CategoryChart({ slug }: { slug: string }) {
  const preset = VISUAL_PRESETS[slug];
  if (!preset) return null;
  const { chart, chartData, primary, accent, chartTitle } = preset;

  return (
    <Card className="border-border/60 bg-card/80 backdrop-blur-sm">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-primary" />
            {chartTitle}
          </CardTitle>
          <span className="text-xs text-muted-foreground">Illustrative</span>
        </div>
      </CardHeader>
      <CardContent className="h-[260px]">
        <ResponsiveContainer width="100%" height="100%">
          {chart === "area" ? (
            <AreaChart data={chartData}>
              <defs>
                <linearGradient id={`grad-${slug}`} x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={primary} stopOpacity={0.6} />
                  <stop offset="100%" stopColor={primary} stopOpacity={0.05} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <Tooltip contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 12 }} />
              <Area type="monotone" dataKey="value" stroke={primary} strokeWidth={2} fill={`url(#grad-${slug})`} />
            </AreaChart>
          ) : chart === "bar" ? (
            <BarChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <Tooltip contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 12 }} />
              {("portfolio" in (chartData[0] || {})) ? (
                <>
                  <Bar dataKey="portfolio" fill={primary} radius={[6, 6, 0, 0]} />
                  <Bar dataKey="benchmark" fill={accent} radius={[6, 6, 0, 0]} />
                </>
              ) : (
                <Bar dataKey="value" fill={primary} radius={[6, 6, 0, 0]} />
              )}
            </BarChart>
          ) : chart === "stacked" ? (
            <BarChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <Tooltip contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="listed" stackId="a" fill={primary} radius={[0, 0, 0, 0]} />
              <Bar dataKey="private" stackId="a" fill={accent} radius={[6, 6, 0, 0]} />
            </BarChart>
          ) : chart === "line" ? (
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} />
              <Tooltip contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 12 }} />
              <Line type="monotone" dataKey="value" stroke={primary} strokeWidth={2.5} dot={{ fill: primary, r: 3 }} />
            </LineChart>
          ) : chart === "radar" ? (
            <RadarChart data={chartData}>
              <PolarGrid stroke="hsl(var(--border))" />
              <PolarAngleAxis dataKey="factor" tick={{ fill: "hsl(var(--muted-foreground))", fontSize: 11 }} />
              <PolarRadiusAxis tick={{ fill: "hsl(var(--muted-foreground))", fontSize: 10 }} />
              <Radar dataKey="A" stroke={primary} fill={primary} fillOpacity={0.4} />
            </RadarChart>
          ) : (
            <PieChart>
              <Tooltip contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 12 }} />
              <Pie data={chartData} dataKey="value" nameKey="name" innerRadius={60} outerRadius={95} paddingAngle={3}>
                {chartData.map((_, i) => (
                  <Cell key={i} fill={[primary, accent, "hsl(38 92% 50%)", "hsl(173 80% 40%)"][i % 4]} />
                ))}
              </Pie>
            </PieChart>
          )}
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default function EnterpriseDataCategory() {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const category = ENTERPRISE_CATEGORIES.find((c) => c.slug === slug);
  const preset = slug ? VISUAL_PRESETS[slug] : undefined;
  const cacheKey = `fp-enterprise-explainer:${slug}`;

  const cached = useMemo<Explainer | null>(() => {
    if (!slug) return null;
    try {
      const raw = sessionStorage.getItem(cacheKey);
      return raw ? JSON.parse(raw) : null;
    } catch {
      return null;
    }
  }, [slug, cacheKey]);

  const [explainer, setExplainer] = useState<Explainer | null>(cached);
  const [loading, setLoading] = useState(!cached);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!category || !preset) return;
    if (cached) return; // already have it
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const { data, error } = await supabase.functions.invoke(
          "enterprise-category-explainer",
          { body: { category: category.label } },
        );
        if (cancelled) return;
        if (error) throw error;
        if (data?.explainer) {
          setExplainer(data.explainer);
          try { sessionStorage.setItem(cacheKey, JSON.stringify(data.explainer)); } catch {}
        } else {
          throw new Error(data?.error || "No explainer returned");
        }
      } catch (e: any) {
        if (!cancelled) setError(e.message || "Failed to generate explainer");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [category, preset, cached, cacheKey]);

  if (!category || !preset) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-6 text-center">
        <div>
          <h1 className="text-2xl font-bold mb-2">Category not found</h1>
          <Button onClick={() => navigate("/")}>Back to home</Button>
        </div>
      </div>
    );
  }

  const Icon = category.icon;
  // Use AI content when ready, otherwise instant fallback
  const display = explainer ?? {
    headline: preset.fallbackHeadline,
    intro: preset.fallbackIntro,
    sections: [],
    capabilities: [],
    dataPoints: preset.fallbackPoints,
    useCases: [],
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Top nav */}
      <header className="border-b bg-background/95 backdrop-blur-md sticky top-0 z-40">
        <div className="container mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <img src={flowpulseLogo} alt="FlowPulse" className="h-8 w-8" />
            <span className="font-bold">FlowPulse</span>
          </Link>
          <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
            <ArrowLeft className="h-4 w-4 mr-2" /> Back to home
          </Button>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden py-16 md:py-20">
        <div
          className="absolute inset-0 opacity-[0.06]"
          style={{
            background: `radial-gradient(circle at 20% 30%, ${preset.primary} 0%, transparent 45%), radial-gradient(circle at 80% 70%, ${preset.accent} 0%, transparent 45%)`,
          }}
        />
        <div className="relative container mx-auto px-6 max-w-5xl text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-primary/10 border border-primary/20 rounded-full mb-6">
            <Sparkles className="h-3.5 w-3.5 text-primary" />
            <span className="text-xs font-semibold text-primary uppercase tracking-wider">
              Enterprise Data
            </span>
          </div>
          <div
            className="inline-flex h-16 w-16 items-center justify-center rounded-2xl shadow-lg mb-6"
            style={{ background: `linear-gradient(135deg, ${preset.primary}, ${preset.accent})` }}
          >
            <Icon className="h-8 w-8 text-white" strokeWidth={1.5} />
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4">
            {category.label}
          </h1>
          <p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
            {display.headline}
          </p>
        </div>
      </section>

      {/* Body */}
      <section className="container mx-auto px-6 max-w-6xl pb-16 md:pb-24 space-y-12">
        {/* Intro + Chart */}
        <div className="grid lg:grid-cols-5 gap-6">
          <Card className="lg:col-span-2 border-border/60 bg-card/80 backdrop-blur-sm">
            <CardContent className="p-6 md:p-7">
              <p className="text-base md:text-lg leading-relaxed">{display.intro}</p>
            </CardContent>
          </Card>
          <div className="lg:col-span-3">
            <CategoryChart slug={slug!} />
          </div>
        </div>

        {/* Data points */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {display.dataPoints.map((dp, i) => (
            <Card key={i} className="border-border/60 bg-card/80 backdrop-blur-sm">
              <CardContent className="p-5 text-center">
                <div
                  className="text-2xl md:text-3xl font-bold bg-clip-text text-transparent"
                  style={{ backgroundImage: `linear-gradient(135deg, ${preset.primary}, ${preset.accent})` }}
                >
                  {dp.value}
                </div>
                <div className="text-xs uppercase tracking-wider text-muted-foreground mt-1">
                  {dp.label}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Sections */}
        {loading && !explainer ? (
          <div className="grid md:grid-cols-2 gap-6">
            {[0, 1, 2, 3].map((i) => (
              <Card key={i} className="border-border/60">
                <CardContent className="p-6 space-y-3">
                  <Skeleton className="h-5 w-1/3" />
                  <Skeleton className="h-3 w-full" />
                  <Skeleton className="h-3 w-5/6" />
                  <Skeleton className="h-3 w-4/6" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          display.sections.length > 0 && (
            <div className="grid md:grid-cols-2 gap-6">
              {display.sections.map((sec, i) => (
                <Card key={i} className="border-border/60 hover:border-primary/40 transition-colors">
                  <CardContent className="p-6">
                    <h3 className="text-xl font-bold mb-3">{sec.title}</h3>
                    <p className="text-muted-foreground leading-relaxed">{sec.body}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          )
        )}

        {/* Capabilities */}
        {display.capabilities.length > 0 && (
          <Card className="border-border/60 bg-gradient-to-br from-card to-muted/30">
            <CardContent className="p-6 md:p-8">
              <h3 className="text-2xl font-bold mb-6">Core capabilities</h3>
              <div className="grid md:grid-cols-2 gap-3">
                {display.capabilities.map((cap, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-background/60 border border-border/50">
                    <CheckCircle2 className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
                    <span>{cap}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Use cases */}
        {display.useCases.length > 0 && (
          <div>
            <h3 className="text-2xl md:text-3xl font-bold mb-6 text-center">
              Built for these workflows
            </h3>
            <div className="grid md:grid-cols-3 gap-6">
              {display.useCases.map((uc, i) => (
                <Card key={i} className="border-border/60 hover:border-primary/40 transition-colors">
                  <CardContent className="p-6">
                    <h4 className="font-bold mb-2">{uc.title}</h4>
                    <p className="text-sm text-muted-foreground">{uc.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        )}

        {error && !loading && (
          <p className="text-center text-sm text-muted-foreground">
            (Live AI explainer unavailable — showing cached overview.)
          </p>
        )}
      </section>

      {/* Contact form */}
      <section className="bg-muted/30 border-t py-16 md:py-24">
        <div className="container mx-auto px-6 max-w-3xl">
          <div className="text-center mb-10">
            <h2 className="text-3xl md:text-4xl font-bold mb-3">
              Talk to our enterprise team
            </h2>
            <p className="text-muted-foreground text-lg">
              Tell us about your {category.label.toLowerCase()} requirements — a
              FlowPulse specialist will be in touch within 24 hours.
            </p>
          </div>
          <ContactForm sourcePage={`enterprise-data:${slug}`} />
        </div>
      </section>
    </div>
  );
}
