import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { generateFinancialReport } from "@/utils/pdfGenerator";

export interface ReportSection {
  id: string;
  title: string;
  content: string;
  enabled?: boolean;
}

export interface ReportContext {
  clientName?: string;
  moduleName: string;
  sections: ReportSection[];
  metadata?: Record<string, string | number>;
}

interface ClientReportGeneratorProps {
  context: ReportContext;
  clientName?: string;
  trigger?: React.ReactNode;
  className?: string;
}

type ReportType = "executive" | "comprehensive";

export function ClientReportGenerator({
  context,
  clientName,
  trigger,
  className,
}: ClientReportGeneratorProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [reportType, setReportType] = useState<ReportType>("executive");
  const [selectedSections, setSelectedSections] = useState<Set<string>>(
    new Set(context.sections.map(s => s.id))
  );
  const [isGenerating, setIsGenerating] = useState(false);

  const toggleSection = (id: string) => {
    setSelectedSections(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const generateReport = async () => {
    setIsGenerating(true);
    try {
      const activeSections = context.sections.filter(s => selectedSections.has(s.id));

      if (activeSections.length === 0) {
        toast.error("Please select at least one section");
        return;
      }

      const name = clientName || context.clientName || "Client";
      const isExecutive = reportType === "executive";

      // Build report content
      let content = "";

      // Metadata summary
      if (context.metadata) {
        content += "Summary Overview:\n\n";
        Object.entries(context.metadata).forEach(([key, value]) => {
          const formattedKey = key.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase());
          content += `${formattedKey}: ${typeof value === "number" ? `£${value.toLocaleString()}` : value}\n`;
        });
        content += "\n---\n\n";
      }

      // Report sections
      activeSections.forEach(section => {
        content += `${section.title}:\n\n`;
        if (isExecutive) {
          // Truncate to first 3 paragraphs for executive summary
          const paragraphs = section.content.split("\n\n").filter(p => p.trim());
          content += paragraphs.slice(0, 3).join("\n\n");
        } else {
          content += section.content;
        }
        content += "\n\n---\n\n";
      });

      // Disclaimer
      content += "Important Disclaimer:\n\n";
      content += "This report is generated by FlowPulse.io and is intended for informational purposes only. ";
      content += "It does not constitute financial advice. Past performance is not indicative of future results. ";
      content += "Please consult with a qualified financial advisor before making investment decisions.\n\n";
      content += `Report generated on ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`;

      const title = isExecutive
        ? `Executive Summary — ${name} — ${context.moduleName}`
        : `Comprehensive Report — ${name} — ${context.moduleName}`;

      generateFinancialReport({
        title,
        content,
        generatedBy: "FlowPulse Financial Advisory Platform",
        date: new Date(),
      });

      toast.success(`${isExecutive ? "Executive summary" : "Comprehensive report"} generated`);
      setIsOpen(false);
    } catch (error) {
      console.error("Report generation error:", error);
      toast.error("Failed to generate report");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="sm" className={className}>
            <FileText className="h-4 w-4 mr-2" />
            Generate Report
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Generate Client Report
          </DialogTitle>
          <DialogDescription>
            {context.moduleName} report{clientName ? ` for ${clientName}` : ""}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Report type */}
          <div className="space-y-2">
            <Label>Report Type</Label>
            <Select value={reportType} onValueChange={(v) => setReportType(v as ReportType)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="executive">Executive Summary (1–2 pages)</SelectItem>
                <SelectItem value="comprehensive">Comprehensive Report (Full detail)</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Section selection */}
          <div className="space-y-2">
            <Label>Include Sections</Label>
            <ScrollArea className="h-48 border rounded-md p-3">
              <div className="space-y-3">
                {context.sections.map(section => (
                  <div key={section.id} className="flex items-start gap-3">
                    <Checkbox
                      id={section.id}
                      checked={selectedSections.has(section.id)}
                      onCheckedChange={() => toggleSection(section.id)}
                    />
                    <label htmlFor={section.id} className="text-sm leading-tight cursor-pointer">
                      {section.title}
                    </label>
                  </div>
                ))}
              </div>
            </ScrollArea>
            <div className="flex gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="text-xs h-7"
                onClick={() => setSelectedSections(new Set(context.sections.map(s => s.id)))}
              >
                Select all
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="text-xs h-7"
                onClick={() => setSelectedSections(new Set())}
              >
                Deselect all
              </Button>
            </div>
          </div>

          <Button onClick={generateReport} disabled={isGenerating} className="w-full">
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Generate {reportType === "executive" ? "Executive Summary" : "Comprehensive Report"}
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
