import jsPDF from 'jspdf';

interface ReportData {
  title: string;
  content: string;
  generatedBy?: string;
  date?: Date;
}

export const generateFinancialReport = (data: ReportData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  // ============ FRONT PAGE ============
  // Gradient background
  doc.setFillColor(135, 206, 250); // Shiny baby blue
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Company name - centered and large
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(42);
  doc.setFont('helvetica', 'bold');
  const companyName = 'FlowPulse.io';
  const companyWidth = doc.getTextWidth(companyName);
  doc.text(companyName, (pageWidth - companyWidth) / 2, 100);
  
  // Tagline
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  const tagline = 'Financial Advisory Platform';
  const taglineWidth = doc.getTextWidth(tagline);
  doc.text(tagline, (pageWidth - taglineWidth) / 2, 115);
  
  // Report title box
  doc.setFillColor(0, 0, 0, 0.1);
  doc.roundedRect((pageWidth - 140) / 2, 140, 140, 40, 5, 5, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(data.title, 130);
  let titleY = 155;
  titleLines.forEach((line: string) => {
    const lineWidth = doc.getTextWidth(line);
    doc.text(line, (pageWidth - lineWidth) / 2, titleY);
    titleY += 8;
  });
  
  // Date at bottom
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const dateStr = (data.date || new Date()).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  const dateWidth = doc.getTextWidth(dateStr);
  doc.text(dateStr, (pageWidth - dateWidth) / 2, pageHeight - 30);
  
  if (data.generatedBy) {
    const byText = `Prepared by: ${data.generatedBy}`;
    const byWidth = doc.getTextWidth(byText);
    doc.text(byText, (pageWidth - byWidth) / 2, pageHeight - 20);
  }
  
  // ============ CONTENT PAGES ============
  doc.addPage();
  
  // Header on content pages
  doc.setFillColor(135, 206, 250);
  doc.rect(0, 0, pageWidth, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FlowPulse.io', margin, 16);
  
  // Content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const lines = doc.splitTextToSize(data.content, contentWidth);
  let yPosition = 40;
  const lineHeight = 7;
  
  lines.forEach((line: string) => {
    // Check if we need a new page
    if (yPosition > pageHeight - margin - 20) {
      doc.addPage();
      
      // Add header on new pages
      doc.setFillColor(135, 206, 250);
      doc.rect(0, 0, pageWidth, 25, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('FlowPulse.io', margin, 16);
      doc.setTextColor(100, 100, 100);
      doc.setFontSize(10);
      doc.text(`Page ${doc.internal.pages.length - 1}`, pageWidth - margin - 20, 16);
      
      yPosition = 40;
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
    }
    
    doc.text(line, margin, yPosition);
    yPosition += lineHeight;
  });
  
  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This report is generated by FlowPulse.io AI Assistant', margin, footerY);
  doc.text('Confidential & Proprietary', pageWidth - margin - 40, footerY);
  
  // Save the PDF
  const filename = `FlowPulse_${data.title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  doc.save(filename);
};
