import jsPDF from 'jspdf';

interface ReportData {
  title: string;
  content: string;
  generatedBy?: string;
  date?: Date;
}

export const generateFinancialReport = (data: ReportData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  // Header with FlowPulse.io branding
  doc.setFillColor(59, 130, 246); // Primary blue
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('FlowPulse.io', margin, 25);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Financial Advisory Platform', margin, 33);
  
  // Report title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, 60);
  
  // Metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const dateStr = (data.date || new Date()).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  doc.text(`Generated: ${dateStr}`, margin, 70);
  
  if (data.generatedBy) {
    doc.text(`By: ${data.generatedBy}`, margin, 76);
  }
  
  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 82, pageWidth - margin, 82);
  
  // Content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const lines = doc.splitTextToSize(data.content, contentWidth);
  let yPosition = 95;
  const lineHeight = 7;
  
  lines.forEach((line: string, index: number) => {
    // Check if we need a new page
    if (yPosition > pageHeight - margin - 20) {
      doc.addPage();
      yPosition = margin;
      
      // Add header on new page
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('FlowPulse.io', margin, yPosition);
      doc.text(`Page ${doc.internal.pages.length - 1}`, pageWidth - margin - 20, yPosition);
      yPosition += 15;
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
    }
    
    doc.text(line, margin, yPosition);
    yPosition += lineHeight;
  });
  
  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This report is generated by FlowPulse.io AI Assistant', margin, footerY);
  doc.text('Confidential & Proprietary', pageWidth - margin - 40, footerY);
  
  // Save the PDF
  const filename = `FlowPulse_${data.title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  doc.save(filename);
};
