// Promote an analyst brief into the public.opportunities table.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const ANON = Deno.env.get("SUPABASE_ANON_KEY")!;

    const authHeader = req.headers.get("Authorization") || "";
    const userClient = createClient(SUPABASE_URL, ANON, { global: { headers: { Authorization: authHeader } } });
    const { data: { user } } = await userClient.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const sb = createClient(SUPABASE_URL, SERVICE_KEY);
    const { data: roleRow } = await sb.from("user_roles").select("role").eq("user_id", user.id).eq("role", "admin").maybeSingle();
    if (!roleRow) return new Response(JSON.stringify({ error: "Admin only" }), { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const body = await req.json();
    const { brief_id } = body;
    const rawPlatform = (body.platform || "both").toString().toLowerCase();
    const allowed = ["finance", "investor", "both"];
    const platform = allowed.includes(rawPlatform) ? rawPlatform : "both";

    const { data: brief, error: be } = await sb.from("analyst_briefs").select("*").eq("id", brief_id).single();
    if (be || !brief) throw new Error("Brief not found");

    const targets = platform === "both" ? ["finance", "investor"] : [platform];
    const baseRef = `AI-${brief.id.replace(/-/g, "").slice(0, 8).toUpperCase()}`;

    const insertedIds: string[] = [];
    for (const target of targets) {
      const ref = targets.length > 1 ? `${baseRef}-${target.slice(0, 3).toUpperCase()}` : baseRef;
      const { data: opp, error: oe } = await sb.from("opportunities").insert({
        ref_number: ref,
        title: brief.title,
        short_description: (brief.thesis || brief.title).slice(0, 480),
        industry: brief.category,
        location: "Global",
        business_description: brief.full_markdown,
        industry_overview: brief.catalyst,
        business_highlights: [
          `Conviction: ${brief.conviction}/5`,
          `Score: ${brief.opportunity_score}/100`,
          `Risk: ${brief.risk_score}/100`,
          `Persona: ${brief.persona}`,
          `Horizon: ${brief.time_horizon || "n/a"}`,
        ],
        financial_summary: brief.key_levels || null,
        team_overview: `Generated by FlowPulse Analyst AI (${brief.persona}). All values in GBP.`,
        status: "published",
        platform: target,
      }).select("id").single();
      if (oe) throw oe;
      insertedIds.push(opp.id);
    }

    await sb.from("analyst_briefs").update({
      status: "promoted",
      promoted_opportunity_id: insertedIds[0],
      reviewed_by: user.id,
      reviewed_at: new Date().toISOString(),
    }).eq("id", brief_id);

    return new Response(JSON.stringify({ success: true, opportunity_ids: insertedIds, platform }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error(e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
